version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "weekly"
    reviewers:
      - "quay/babysitters"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel/*"
      golang-x:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: "gomod"
    directory: "/config"
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "weekly"
    reviewers:
      - "quay/babysitters"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel/*"
      golang-x:
        patterns:
          - "golang.org/x/*"
